# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Kuru Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kuru Example
  pod 'Kuru', :path => '../'

  target 'Kuru ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kuru ExampleUITests' do
    # Pods for testing
  end

end
