os: osx
osx_image: xcode12.2
language: swift

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
stages:
  - name: lint
    if: NOT branch =~ ^\d+\.\d+\.\d+$
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$
jobs:
  include:
    - &pod
      stage: lint
      osx_image: xcode12.2
      env: SWIFT=5.2
      cache: cocoapods
      install: gem install cocoapods -v '~> 1.7.0'
      script: pod lib lint Kuru.podspec --allow-warnings --fail-fast --swift-version=$SWIFT
    
    - name: '`pod trunk push`'
      stage: deploy
      osx_image: xcode12.2
      env: SWIFT=5.2
      cache: cocoapods
      install: gem install cocoapods -v '~> 1.7.0'
      script: pod trunk push --verbose --allow-warnings